# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_getdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='number_of_groups',
            field=models.IntegerField(default=0),
        ),
    ]
