# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_groups_number_of_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='number_of_groups',
        ),
        migrations.AddField(
            model_name='getdata',
            name='number_of_groups',
            field=models.IntegerField(default=0),
        ),
    ]
